export const projects = [
  {
    title: 'TriceraCops',
    description: "A dinosaur themed murder mystery game, built using React.js, written in JSX and styled with Bootstrap. All artwork is original. The game sets you in a room of a crime, you must find clues to solve the murder.",
      image: '/images/1.png',
      tags: ['React', 'JSX', 'Bootstrap'],
    source: 'https://github.com/SeanEmmers/tricera-cops',
    visit: 'https://tricera-cops.herokuapp.com/',
    id: 0,
  },
  {
    title: 'AceBook',
    description:"A full stack web app inspired by the functionality of Facebook. Created using Ruby on Rails, styled with Bulma and stored using PostgreSQL. The project is tested with RSpec, Capybara and linted with Rubocop.",
    image: '/images/2.png',
    tags: ['Ruby', 'Rails', 'Bulma', 'PostgreSQL'],
    source: 'https://github.com/SeanEmmers/acebook-rails-soda',
    id: 1,
  },
  {
    title: 'Notes App',
    description: "A web app built to a user specification. The app includes the functionality for taking notes, inserting emoji's into the note via an API call, deleted notes and viewing notes. The code was testing by building our own test suite.",
      image: '/images/3.png',
      tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/SeanEmmers/notes_app',
    id: 2,
  },
  {
    title: 'DogBnB',
    description: "A full stack web app inspired by the functionality of AirBnb. Created using Ruby and Sinatra. Styled using CSS and stored using PostgreSQL and the PG gem. Tested with RSpec and Capybara and linted with Rubocop",
    image: '/images/4.png',
    tags: ['Ruby', 'Sinatra', 'PostgreSQL'],
    source: 'https://github.com/SeanEmmers/dogbnb',
    id: 3,
  },
];